---
name: Linux Build

on:
  push:

jobs:
  numpy:
    name: "Python ${{ matrix.python-version }}-${{ matrix.version.platform }}-np-${{ matrix.version.numpy-version }}"
    runs-on: ${{ matrix.version.platform }}
    env:
      USING_COVERAGE: '3.6,3.7,3.8,3.9'

    strategy:
      fail-fast: False
      matrix:
        python-version:
         - "3.6"
         - "3.7"
         - "3.8"
         - "3.9"
        version:
         - {platform: "ubuntu-20.04", numpy-version: "1.19.4"}

    steps:

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps numpy=${{ matrix.version.numpy-version }} --wheel-dir ./wheels/numpy --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "numpy-${{ matrix.version.numpy-version }}-py${{ matrix.python-version }}-${{ matrix.version.platform }}"
          path: ./wheels/*.whl
