---
name: Linux Build

on:
  push:

jobs:
  numpy:
    name: "Python 3.10-${{ matrix.version.platform }}-np-${{ matrix.version.numpy-version }}"
    runs-on: ${{ matrix.version.platform }}

    strategy:
      fail-fast: False
      matrix:
        version:
         - {platform: "ubuntu-20.04", numpy-version: "1.19.4"}

    steps:

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10.0-alpha.3"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install git+https://github.com/pypa/pip@cfa013b91726dfcbadbff86b29c13df7eeef4d43 --upgrade
          python -m pip install "setuptools<49.2.0" "wheel>=0.36.2"
          python -m pip install git+https://github.com/cython/cython@5377ae7973bbfa89aa5431fb3e5f5b133231e6ba

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps numpy==${{ matrix.version.numpy-version }} --no-build-isolation --wheel-dir ./wheels/numpy --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "numpy-${{ matrix.version.numpy-version }}-${{ matrix.version.platform }}"
          path: ./wheels/numpy/*.whl

  pandas:
    needs: numpy
    name: "Python 3.10-${{ matrix.version.platform }}-np-${{ matrix.version.numpy-version }}-pd-${{ matrix.version.pandas-version }}"
    runs-on: ${{ matrix.version.platform }}

    strategy:
      fail-fast: False
      matrix:
        version:
         - {platform: "ubuntu-20.04", numpy-version: "1.19.4", pandas-version: "1.2.0rc0"}
         - {platform: "ubuntu-20.04", numpy-version: "1.19.4", pandas-version: "1.1.5"}
         - {platform: "ubuntu-20.04", numpy-version: "1.19.4", pandas-version: "1.0.5"}

    steps:

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10.0-alpha.3"

      - name: Download Numpy Wheel
        uses: actions/download-artifact@v2
        with:
          name: "numpy-${{ matrix.version.numpy-version }}-${{ matrix.version.platform }}"
          path: ./wheels/numpy/


      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install git+https://github.com/pypa/pip@cfa013b91726dfcbadbff86b29c13df7eeef4d43 --upgrade
          python -m pip install setuptools "wheel>=0.36.2"
          python -m pip install git+https://github.com/cython/cython@5377ae7973bbfa89aa5431fb3e5f5b133231e6ba
          python -m pip install ./wheels/numpy/*.whl

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps pandas==${{ matrix.version.pandas-version }} --no-build-isolation --wheel-dir ./wheels/pandas --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "pandas-${{ matrix.version.pandas-version }}-${{ matrix.version.platform }}"
          path: ./wheels/pandas/*.whl

  matplotlib:
    needs: numpy
    name: "Python 3.10-${{ matrix.version.platform }}-np-${{ matrix.version.numpy-version }}-mpl-${{ matrix.version.matplotlib-version }}"
    runs-on: ${{ matrix.version.platform }}

    strategy:
      fail-fast: False
      matrix:
        version:
         - {platform: "ubuntu-20.04", numpy-version: "1.19.4", matplotlib-version: "3.3.3"}
         - {platform: "ubuntu-20.04", numpy-version: "1.19.4", matplotlib-version: "3.2.2"}

    steps:

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10.0-alpha.3"

      - name: Download Numpy Wheel
        uses: actions/download-artifact@v2
        with:
          name: "numpy-${{ matrix.version.numpy-version }}-${{ matrix.version.platform }}"
          path: ./wheels/numpy/

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install git+https://github.com/pypa/pip@cfa013b91726dfcbadbff86b29c13df7eeef4d43 --upgrade
          python -m pip install setuptools "wheel>=0.36.2" "certifi>=2020.06.20"
          python -m pip install ./wheels/numpy/*.whl

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps matplotlib==${{ matrix.version.matplotlib-version }} --no-build-isolation --wheel-dir ./wheels/matplotlib --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "matplotlib-${{ matrix.version.matplotlib-version }}-${{ matrix.version.platform }}"
          path: ./wheels/matplotlib/*.whl
