---
name: Windows Build

on:
  push:
    branches: ["master"]

jobs:
  pywin32:
    name: "Python 3.10-${{ matrix.version.platform }}-pywin32-${{ matrix.version.pywin32-version }}"
    runs-on: ${{ matrix.version.platform }}

    strategy:
      fail-fast: False
      matrix:
        version:
         - {platform: "windows-2019", pywin32-version: "300"}

    steps:
      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10.0-beta.1"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install pip --upgrade
          python -m pip install "setuptools<49.2.0" "wheel>=0.36.2"

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps git+https://github.com/mhammond/pywin32 --no-build-isolation --wheel-dir ./wheels/pywin32 --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "pywin32-${{ matrix.version.pywin32-version }}-${{ matrix.version.platform }}"
          path: ./wheels/pywin32/*.whl

  pyreadline:
    name: "Python 3.10-${{ matrix.version.platform }}-pyreadline-${{ matrix.version.pyreadline-version }}"
    runs-on: ${{ matrix.version.platform }}

    strategy:
      fail-fast: False
      matrix:
        version:
         - {platform: "windows-2019", pyreadline-version: "2.0"}

    steps:
      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10.0-beta.1"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install pip --upgrade
          python -m pip install "setuptools<49.2.0" "wheel>=0.36.2"

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps git+https://github.com/osrf/pyreadline --no-build-isolation --wheel-dir ./wheels/pyreadline --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "pyreadline-${{ matrix.version.pyreadline-version }}-${{ matrix.version.platform }}"
          path: ./wheels/pyreadline/*.whl

  numpy:
    name: "Python 3.10-${{ matrix.version.platform }}-np-${{ matrix.version.numpy-version }}"
    runs-on: ${{ matrix.version.platform }}

    strategy:
      fail-fast: False
      matrix:
        version:
         - {platform: "windows-2019", numpy-version: "1.19.3"}
         - {platform: "windows-2019", numpy-version: "1.20.0"}

    steps:
      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10.0-beta.1"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install pip --upgrade
          python -m pip install "setuptools<49.2.0" "wheel>=0.36.2"
          python -m pip install cython --upgrade

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps numpy==${{ matrix.version.numpy-version }} --no-build-isolation --wheel-dir ./wheels/numpy --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "numpy-${{ matrix.version.numpy-version }}-${{ matrix.version.platform }}"
          path: ./wheels/numpy/*.whl

  pandas:
#    needs: numpy
    name: "Python 3.10-${{ matrix.version.platform }}-np-${{ matrix.version.numpy-version }}-pd-${{ matrix.version.pandas-version }}"
    runs-on: ${{ matrix.version.platform }}

    strategy:
      fail-fast: False
      matrix:
        version:
         - {platform: "windows-2019", numpy-version: "1.19.3", pandas-version: "1.1.5"}

    steps:
      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10.0-beta.1"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install pip --upgrade
          python -m pip install setuptools "wheel>=0.36.2"
          python -m pip install cython --upgrade
          python -m pip install "numpy @ https://github.com/domdfcoding/3.10-Wheels/raw/7f2832a5f712b5a0674c534e42dbf3dbacd75377/numpy-1.19.3-cp310-cp310-win_amd64.whl"

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps pandas==${{ matrix.version.pandas-version }} --no-build-isolation --wheel-dir ./wheels/pandas --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "pandas-${{ matrix.version.pandas-version }}-${{ matrix.version.platform }}"
          path: ./wheels/pandas/*.whl

  matplotlib:
#    needs: numpy
    name: "Python 3.10-${{ matrix.version.platform }}-np-${{ matrix.version.numpy-version }}-mpl-${{ matrix.version.matplotlib-version }}"
    runs-on: ${{ matrix.version.platform }}

    strategy:
      fail-fast: False
      matrix:
        version:
         - {platform: "windows-2019", numpy-version: "1.19.3", matplotlib-version: "3.3.3"}

    steps:
      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10.0-beta.1"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install pip --upgrade
          python -m pip install setuptools "wheel>=0.36.2" "certifi>=2020.06.20"
          python -m pip install "numpy @ https://github.com/domdfcoding/3.10-Wheels/raw/7f2832a5f712b5a0674c534e42dbf3dbacd75377/numpy-1.19.3-cp310-cp310-win_amd64.whl"

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps matplotlib==${{ matrix.version.matplotlib-version }} --no-build-isolation --wheel-dir ./wheels/matplotlib --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "matplotlib-${{ matrix.version.matplotlib-version }}-${{ matrix.version.platform }}"
          path: ./wheels/matplotlib/*.whl

#
#  coverage:
#    name: "Python 3.10-${{ matrix.version.platform }}-coverage-${{ matrix.version.coverage-version }}"
#    runs-on: ${{ matrix.version.platform }}
#
#    strategy:
#      fail-fast: False
#      matrix:
#        version:
#         - {platform: "windows-2019", coverage-version: "5.3"}
#
#    steps:
#      - name: Setup Python 🐍
#        uses: "actions/setup-python@v2"
#        with:
#          python-version: "3.10.0-beta.1"
#
#      - name: Install dependencies 🔧
#        run: |
#          python -VV
#          python -m site
#          python -m pip install pip --upgrade
#          python -m pip install "setuptools>=41.2" "wheel>=0.36.2"
#
#      - name: "Build Wheel"
#        run: "python -m pip wheel --no-deps coverage==${{ matrix.version.coverage-version }} --no-build-isolation --wheel-dir ./wheels/coverage --verbose"
#
#      - name: "Upload Artefacts"
#        uses: actions/upload-artifact@v2
#        with:
#          name: "coverage-${{ matrix.version.coverage-version }}-${{ matrix.version.platform }}"
#          path: ./wheels/coverage/*.whl
#
#  kiwisolver:
#    name: "Python 3.10-${{ matrix.version.platform }}-kiwisolver-${{ matrix.version.kiwisolver-version }}"
#    runs-on: ${{ matrix.version.platform }}
#
#    strategy:
#      fail-fast: False
#      matrix:
#        version:
#         - {platform: "windows-2019", kiwisolver-version: "1.3.1"}
#
#    steps:
#      - name: Setup Python 🐍
#        uses: "actions/setup-python@v2"
#        with:
#          python-version: "3.10.0-beta.1"
#
#      - name: Install dependencies 🔧
#        run: |
#          python -VV
#          python -m site
#          python -m pip install pip --upgrade
#          python -m pip install "setuptools>=41.2" "wheel>=0.36.2"
#
#      - name: "Build Wheel"
#        run: "python -m pip wheel --no-deps kiwisolver==${{ matrix.version.kiwisolver-version }} --no-build-isolation --wheel-dir ./wheels/kiwisolver --verbose"
#
#      - name: "Upload Artefacts"
#        uses: actions/upload-artifact@v2
#        with:
#          name: "kiwisolver-${{ matrix.version.kiwisolver-version }}-${{ matrix.version.platform }}"
#          path: ./wheels/kiwisolver/*.whl
